# Generated by Django 5.1.1 on 2024-10-23 18:39

import django.db.models.deletion
import dynamicdns.dns_providers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(choices=[(dynamicdns.dns_providers.Providers['CLOUDFLARE'], 'Cloudflare DNS')], max_length=255)),
                ('auth_token', models.TextField()),
                ('service_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_of_truth', models.CharField(blank=True, max_length=255)),
                ('dynamic_source_of_truth', models.BooleanField(default=True)),
                ('history', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicdns.dnsservice')),
            ],
        ),
    ]
