# Generated by Django 5.1.1 on 2024-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicdns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsservice',
            name='provider',
            field=models.CharField(choices=[('1', 'Cloudflare DNS')], max_length=255),
        ),
    ]
