# Generated by Django 5.1.1 on 2024-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicdns', '0002_alter_dnsservice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredrecord',
            name='interval',
            field=models.CharField(default='* * * * *', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredrecord',
            name='type',
            field=models.CharField(choices=[('1', 'A - IPv4'), ('2', 'AAAA - IPv6')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='dnsservice',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
