# Generated by Django 5.1.1 on 2024-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicdns', '0003_monitoredrecord_interval_monitoredrecord_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsservice',
            name='provider',
            field=models.CharField(choices=[('1', 'Cloudflare DNS'), ('2', 'Namecheap')], max_length=255),
        ),
    ]
